defaults: &defaults
  docker:
    - image: circleci/node:latest-browsers
  working_directory: ~/repo

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  test:
    <<: *defaults
    steps:
      - run:
          name: "JavaScript Linter"
          command: yarn lint --format junit -o reports/junit/js-lint-results.xml

      - store_test_results:
          path: reports/junit

  deploy_master:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Build docker image"
          command: |
            docker build -t $DOCKER_USER/$CIRCLE_PROJECT_REPONAME .

      - deploy:
          name: Push docker image
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push $DOCKER_USER/$CIRCLE_PROJECT_REPONAME

  deploy_tag:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Build docker image"
          command: |
            PACKAGE_VERSION=$(node -p "require('./package.json').version")
            docker build -t $DOCKER_USER/$CIRCLE_PROJECT_REPONAME:$PACKAGE_VERSION .

      - deploy:
          name: Push docker image
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            PACKAGE_VERSION=$(node -p "require('./package.json').version")
            docker push $DOCKER_USER/$CIRCLE_PROJECT_REPONAME:$PACKAGE_VERSION

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - test:
          requires:
            - build
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - deploy_master:
          requires:
            - test
          filters:
            branches:
              only: master
      - deploy_tag:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9](\.[0-9]){2}$/
