version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:latest-browsers

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run:
          name: "JavaScript Linter"
          command: yarn lint --format junit -o reports/junit/js-lint-results.xml

      - store_test_results:
          path: reports/junit

      - setup_remote_docker

      - deploy:
          name: Build and push Docker image if branch is master
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker build -t $DOCKER_USER/$CIRCLE_PROJECT_REPONAME .
              echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
              docker push $DOCKER_USER/$CIRCLE_PROJECT_REPONAME
            fi
